### PR TITLE
PekkoPersistenceJdbcVersion 1.1.0-M1

### PR DESCRIPTION
**Pull request by pjfanning**
see #83

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Nice!

**Comment by raboof** [comment]
Do I understand correctly that we want to tag `v1.1.0-M0` after merging this, to flag that he next release of pekko-persistence-r2dbc after this change should be `v1.1.0`?

**Comment by pjfanning** [comment]
> Do I understand correctly that we want to tag `v1.1.0-M0` after merging this, to flag that he next release of pekko-persistence-r2dbc after this change should be `v1.1.0`?

Makes sense. It was an oversight not to have already added the v1.1.0-M0 tag. We've already got 1.1.0-M1 dependency on pekko-core.

**Comment by pjfanning** [comment]
I had the v1.1.0-M0 tag locally but forgot to push to git remote. Generally, we add that tag when we fork out the 1.0 build from main. I have pushed that tag now.

**Pull request merged**
