### PR TITLE
build with pekko 1.1.0-M1

### PR DESCRIPTION
**Pull request by pjfanning**
* repurpose the nightly tests that test with Pekko 1.1 to use Pekko 1.0

### CODE REVIEW

**Review by He-Pin — COMMENTED** [review]
Lgtm

**Review by He-Pin — APPROVED** [review]
Lgtm

**Comment by raboof** [comment]
link validator failure is because of http://asm.ow2.io/ - is that a new dependency?

**Comment by pjfanning** [comment]
> link validator failure is because of http://asm.ow2.io/ - is that a new dependency?

I ran `sbt dependencyTree` locally and can't find any mentions of asm.

**Pull request merged**
